var str = "Hi my name is Misbah_Sajjad";
var bool = true;
var num = 18 + " year old";
var city = "Karachi";
var arr = ["Misbah", "Sajjad", 18 + " year old", "Karachi"];
var obj = { name: "Misbah", age: 18 + " year old", city: "Karachi" };
console.log('String');
console.log(str);
console.warn('===============');
console.log('Boolean');
console.log(bool);
console.warn('===============');
console.log('Number');
console.log(num);
console.warn('===============');
console.log("City");
console.log(city);
console.warn('===============');
console.log('array');
console.log(arr);
console.warn('===============');
console.log('object');
console.log(obj);
console.warn('===============');
console.log('===============');
console.warn("\"name\" ".concat(str, " \"single\" ").concat(bool, " \"age\" ").concat(num, " \"city\" ").concat(city, " \"array\" ").concat(arr, " \"object\" ").concat(obj));
